// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vacnmkgjwxgtloztxpbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhY25ta2dqd3hndGxvenR4cGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDI1MzUsImV4cCI6MjA3MzE3ODUzNX0.3aXIT_rn3Vmy2pmlCkZUffQDEbYXWqDrM8nxUNrn_hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});